##############################################################################
# Configuration file for the convolutional neural network used in the
# cnn.py file. Make sure that if additional hyperparamters are added to this
# configuration file, they are also present in the cnn.build_model function
#############################################################################

kernel_size:
- 3

epochs:
- 30

layers:
- 4

# Make sure that if the number of layers changes,
# the number of actvation functions should increase/decrease accordingly.
activation:
- 'relu'
- 'relu'
- 'sigmoid'
- 'sigmoid'

pooling:
- 'MaxPool2D'

input_shape:
- 120
- 3

filter_size:
- 4

num_classes:
- 2

# This refers to the optimizer learning rate.
optimizer:
- 'Adam'

learning_rate:
- 0.1e-3

# This refers to the number of epochs after which the model will stop
# if there was no improvement in the loss funciton.
# [used in the callback funciton]
patience:
- 3
