layers:
  - 4

filters:
  - Int
  - values:
    - 2
    - 4
    - 8
    - 16
    - 32

kernel_size:
  - Int
  - values:
    - 3
    - 5

activation:
  - Choice
  - values:
    - relu
    - sigmoid

pooling:
  - Choice
  - values:
    - avg
    - max

optimizer:
  - Choice
  - values:
    - adam
    - SGD

learning_rate:
  - Choice
  - values:
    - 0.1e-4
    - 0.1e-5
    - 0.1e-6
    - 0.1e-7