#########################################################################
# Configuration for running the tuner

num_classes:
  - 4

epochs:
  - 30

patience:
  - 3

input_shape:
  - 100
  - 3

# execution per trial
max_trials:
  - 3

exec_per_trial:
  - 3

search_function:
  - 'RandomSearch'

#########################################################################
# Configuration of search space

layers:
  - 5

filters:
  - Int
  - values:
    - 2
    - 4
    - 8
    - 16
    - 32

kernel_size:
  - Choice
  - values:
    - 3
    - 4
    - 5

activation:
  - Choice
  - values:
    - relu
    - sigmoid

pooling:
  - Choice
  - values:
    - avg
    - max

optimizer:
  - Choice
  - values:
    - adam
    - SGD

learning_rate:
  - Choice
  - values:
    - 0.1e-4
    - 0.1e-5
    - 0.1e-6
    - 0.1e-7
