# Scattering columns
# 0 : Intensity I(Q)
# 1: q

tform_command_list:
    - "lin_q_lin_I"
    - "lin_q_log_I"
    - "log_q_lin_I"
    - "log_q_log_I"
    - "rec_q_lin_I"
    - "rec_q_rec_I"
    - "lin_q_rec_I"
    - "lin_q_sqr_I"
    - "sqr_q_lin_I"
    - "sqr_q_log_I"
    - "log_q_sqr_I"
    - "sqr_q_sqr_I"
    - "der_q_log_I"
    - "log_q_der_I"
    - "der_q_der_I"
    - "multi_transform"




tform_command_dict:
    "lin_q_lin_I":
        - [0, '1d_raw', 1]
        - [1, '1d_raw', 0]
    "lin_q_log_I":
        - [0, '1d_raw', 1]
        - [2, '1d_log', 0]
    "log_q_lin_I":
        - [0, '1d_log', 1]
        - [1, '1d_raw', 0]
    "log_q_log_I":
        - [0, '1d_log', 1]
        - [2, '1d_log', 0]
    "rec_q_lin_I":
        - [2, '1d_reciprocal', 1]
        - [3, '1d_raw', 0]
    "rec_q_rec_I":
        - [0, '1d_reciprocal', 1]
        - [1, '1d_reciprocal', 0]
    "lin_q_rec_I":
        - [0, '1d_raw',1]
        - [1, '1d_reciprocal', 0]
    "lin_q_sqr_I":
        - [0, '1d_raw', 1]
        - [1, '1d_multiply', 0]
    "sqr_q_lin_I":
        - [3, '1d_multiply', 1]
        - [1, '1d_raw', 0]
    "sqr_q_log_I":
        - [5, '1d_multiply', 1]
        - [1, '1d_log', 0]
    "log_q_sqr_I":
        - [0, '1d_log', 1]
        - [1, '1d_multiply', 0]
    "sqr_q_sqr_I":
        - [0, '1d_multiply', 1]
        - [1, '1d_multiply', 0]
    "multi_transform":
        - [0, '1d_raw', 1]
        - [1, '1d_log', 1]
        - [2, '1d_derivative', 1]
        - [3, '1d_raw', 0]
        - [4, '1d_log', 0]
        - [5, '1d_derivative', 0]
    "der_q_log_I":
        - [0, '1d_derivative', 1]
        - [1, '1d_log', 0]
    "log_q_der_I":
        - [0, '1d_log', 1]
        - [2, '1d_derivative', 0]
    "der_q_der_I":
        - [0, '1d_derivative', 1]
        - [1, '1d_derivative', 0]
