
# Configuration File to provide List of Transformation Commands
#   To the Arbitrage.py wrapping function: "####################"
#
# File will contain a List of Tuple-Lists, In the following Format:
#
# LIST_OF_TRANSFORMATIONS:
#       TForm_1 (w/ Name? String for Reference?)
#           -   (
#               (Index=0, transform, source),
#               (Index=1, transform, source),
#               (Index=2, transform, source),
#               (Index=3, transform, source),
#               (Index=4, transform, source),
#               (Index=5, transform, source),
#               )
#
#        Wherein Index will be a number from 0 to 5 representing
#            RGB in X and Y, respecitively.
#           (Actually can re-define RGBrgb Later)
#        Each "transform" will be a function in one of the 1D lists (for now)
#            which should be CALLABLE via the tform_1d1d function.
#        each "source" will be the naturally occuring array number
#            (OR COLUMN NAME?) that will be transformed upon.


# =============================================================================
# # List Of Transformation Commands:
#    "list_1d1d = {
#         "1d_raw": transform_1d_none,
#         "1d_log": transform_1d_log,
#         "1d_exp": transform_1d_exp,
#         "1d_reciprocal": transform_1d_reciprocal,
#         "1d_cumsum": transform_1d_cumsum,
#         "1d_derivative": transform_1d_derivative
#         }"
# =============================================================================


# =============================================================================
#
# # For Planning Purposes, Suggest you Investigate your Data's SOURCE columns
# #   And Post Here to help in planning:
# #   FOR EIS DATA in our Format
#
# #   [0] :   Frequency (Log-like)
# #   [1] :   Angular_Freq (Loglike)
# #   [2] :   Real Z
# #   [3] :   Imaginary Z
# #   [4] :   Total Ohms
# #   [5] :   Phase Angle
# #   [6] : Real Z with Noise (if added)
# #   [7] : Imaginary Z with Noise (if added)
# =============================================================================

tform_command_list:
    - "ReZ_ImZ"
    - "log10_f_ReZ_ImZ"
    - "log10_f_der_ReZ_der_ImZ"
    - "der_ReZ_der_ImZ"
    - "rec_ReZ_ImZ"
    - "ReZ_rec_ImZ"
    - "rec_ReZ_rec_ImZ"
    - "sqr_ReZ_sqr_ImZ"
    - "log10_ReZ_ImZ"
    - "exp_ReZ_exp_ImZ"
    - "exp_ReZ_ImZ"
    - "ReZ_exp_ImZ"
    - "sum_ReZ_ImZ"
    - "ReZ_sum_ImZ"
    - "sum_ReZ_sum_ImZ"

tform_command_dict:
    "ReZ_ImZ":
        - [0, '1d_raw', 6]
        - [2, '1d_raw', 7]

    "log10_f_ReZ_ImZ":
        - [0, '1d_log10', 0]
        - [1, '1d_raw', 6]
        - [2, '1d_raw', 7]

    "log10_f_der_ReZ_der_ImZ":
        - [0, '1d_log10', 0]
        - [1, '1d_derivative', 6]
        - [2, '1d_derivative', 7]

    "der_ReZ_der_ImZ":
        - [0, '1d_derivative', 6]
        - [1, '1d_derivative', 7]

    "rec_ReZ_ImZ":
        - [0, '1d_reciprocal', 6]
        - [2, '1d_raw', 7]

    "ReZ_rec_ImZ":
        - [0, '1d_raw', 6]
        - [2, '1d_reciprocal', 7]

    "rec_ReZ_rec_ImZ":
        - [0, '1d_reciprocal', 6]
        - [1, '1d_reciprocal', 7]

    "sqr_ReZ_sqr_ImZ":
        - [3, '1d_multiply', 6]
        - [4, '1d_multiply', 7]

    "log10_ReZ_ImZ":
        - [1, '1d_log10', 6]
        - [2, '1d_raw', 7]

    "exp_ReZ_exp_ImZ":
        - [1, '1d_exp', 6]
        - [2, '1d_exp', 7]

    "exp_ReZ_ImZ":
        - [1, '1d_exp', 6]
        - [0, '1d_raw', 7]

    "ReZ_exp_ImZ":
        - [0, '1d_raw', 6]
        - [4, '1d_exp', 7]

    "sum_ReZ_ImZ":
        - [5, '1d_cumsum', 6]
        - [2, '1d_raw', 7]

    "ReZ_sum_ImZ":
        - [0, '1d_raw', 6]
        - [4, '1d_cumsum', 7]

    "sum_ReZ_sum_ImZ":
        - [0, '1d_cumsum', 6]
        - [1, '1d_cumsum', 7]
